version: '3.6'

services:
  master:
    image: edcd/coriolis:master
    build:
      dockerfile: Dockerfile
      context: .
      args:
        branch: master
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
    ports:
      - "3305:80"

networks:
  web:
